<?php
/**
 * @author: liaofei<136327134@qq.com>
 * @day: 2020/8/19
 */

namespace crmeb\services\sms\storage;

use crmeb\basic\BaseSms;
use AlibabaCloud\Client\AlibabaCloud;
use AlibabaCloud\Client\Exception\ClientException;
use AlibabaCloud\Client\Exception\ServerException;
use think\exception\ValidateException;

/**
 * 阿里云短信发送
 * Class Aliyun
 * @package crmeb\services\sms\storage
 */
class Aliyun extends BaseSms
{

    /**
     * AccessKeyId
     * @var string
     */
    protected $accessKeyId;

    /**
     * AccessKeySecret
     * @var string
     */
    protected $accessKeySecret;

    /**
     * 签名
     * @var string
     */
    protected $signName;

    /**
     * 区域 默认杭州
     * @var string
     */
    protected $regionId = 'cn-hangzhou';

    /**
     * 初始化
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->accessKeyId = $config['accessKeyId'] ?? null;
        $this->accessKeySecret = $config['accessKeySecret'] ?? null;
        $this->signName = $config['signName'] ?? null;
        if (isset($config['regionId'])) {
            $this->regionId = $config['regionId'];
        }
    }

    /**
     * 初始化阿里云短信
     */
    protected function app()
    {
        // 判断下accessKeyId和accessKeySecret存在
        if (!$this->accessKeyId || !$this->accessKeySecret) {
            throw new ValidateException('请传入阿里云短信配置');
        }
        //调用阿里云SDK初始化
        AlibabaCloud::accessKeyClient($this->accessKeyId, $this->accessKeySecret)
            ->regionId($this->regionId)
            ->asDefaultClient();
    }


    /**
     * 发送短信
     * @param string $phone
     * @param string $templateId
     * @param array $data
     * @return mixed|void
     */
    public function send(string $phone, string $templateId, array $data = [])
    {
        //参数判断
        if (!$phone) {
            throw new ValidateException('请传入手机号');
        }
        if (!$templateId) {
            throw new ValidateException('请传入发送模板id');
        }
        //初始化阿里云SDK
        $this->app();

        try {
            //执行发送
            $result = AlibabaCloud::rpc()
                ->product('Dysmsapi')
                ->version('2017-05-25')
                ->action('SendSms')
                ->method('POST')
                ->host('dysmsapi.aliyuncs.com')
                ->options([
                    'query' => [
                        'RegionId' => $this->regionId,
                        'PhoneNumbers' => $phone,
                        'SignName' => $this->signName,
                        'TemplateCode' => $templateId,
                        'TemplateParam' => json_encode($data),
                    ],
                ])->request()->toArray();
            return $result;
        } catch (ClientException $e) {
            throw new ValidateException($e->getMessage());
        } catch (ServerException $e) {
            throw new ValidateException($e->getMessage());
        }
    }

}